[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
 target-version = ["py311"]
 exclude = '''
 (
        data_sync.py 
    |   format.py 
 )
 '''

 [tool.ruff]
 line-length = 88
 target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E203", "E501"]
exclude = [
    "data_sync.py",
    "format.py"
]

 [tool.pytest.ini_options]
 pythonpath = ["."]
 testpaths = ["tests"]